config/routes.rb
Rails.application.routes.draw do
  root :to => 'toppages#index'
  # resources :teams, only: [:new, :create, :destroy]
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  get '/bosses/new_team', to: 'bosses#new_team'
  patch '/bosses/new_team', to: 'bosses#post_team'

  devise_for :bosses, controllers: {
    registrations: 'bosses/registrations',
    sessions: 'bosses/sessions'
  }

  resources :bosses, only:[:index, :show, :edit, :update]
  resources :users, only:[:index, :show]
  resources :teams, only:[:show] #ボスがチームメンバーの親タスクをまとめて見る用のroutes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # root to: 'tasks'
  resources :parent_tasks do
    member do
      post :done
      post :cansel
    end
    resources :task_comments, only: [:create, :destroy]
    resources :child_tasks do
      collection do
        post :finished
        post :index_canceled
        post :show_canceled
        post :index_result_finish
        post :show_result_finish
      end
    end
  end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boss.rb
class Boss < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :organizations, dependent: :destroy
  has_many :teams, through: :organizations, dependent: :destroy
  has_many :task_comments, dependent: :destroy
  # boss.supervise_teamsでチーム引っ張れる
end

app/models/child_task.rb
class ChildTask < ApplicationRecord
  belongs_to :parent_task
  has_many :task_comments, dependent: :destroy
end

app/models/manager.rb
class Manager < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/organization.rb
class Organization < ApplicationRecord
    belongs_to :team
    belongs_to :boss
end

app/models/parent_task.rb
class ParentTask < ApplicationRecord
    belongs_to :user
    has_many :child_tasks, dependent: :destroy
    has_many :task_comments, dependent: :destroy
end

app/models/task_comment.rb
class TaskComment < ApplicationRecord
  validates :parent_comment, length: { maximum: 255 }
  validates :child_comment, length: { maximum: 255 }

  belongs_to :user, optional: true
  belongs_to :parent_task, optional: true
  belongs_to :child_task, optional: true
  belongs_to :boss, optional: true
end

app/models/team.rb
class Team < ApplicationRecord

    has_many :users, dependent: :destroy
    has_many :organizations, dependent: :destroy
    has_many :bosses, through: :organizations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 50 }

  belongs_to :team
  has_many :parent_tasks, dependent: :destroy
  has_many :task_comments, dependent: :destroy
end

app/controllers/bosses_controller.rb
class BossesController < ApplicationController
  before_action { :authenticate_user! || :authenticate_boss!}
  def index
    @bosses = Boss.all
  end

  def show
    @boss=Boss.find(params[:id])
  end


  def update
    # binding.pry
    if current_boss.id != params[:id].to_i
      redirect_to boss_path
    else
      current_boss.organizations.each do |organization|
        organization.destroy
      end

      # binding.pry
      params["boss"]["team_ids"].each do |t|
        if Organization.find_by(boss_id: current_boss.id, team_id: t)
          next
        else
          current_boss.organizations.create(team_id: t).save
        end
      end
      redirect_to "/bosses/#{params[:id]}"
    end
  end

  def new_team
    @boss=Boss.find(current_boss.id)
    # @boss.organizations.build
    @teams=Team.all
  end

  def post_team
    params["boss"]["team_ids"].each do |t|
      if Organization.find_by(boss_id: current_boss.id, team_id: t)
        next
      else
        current_boss.organizations.create(team_id: t).save
      end
    end
    redirect_to :root
  end

  def boss_params
    params.require(:boss).permit(team_ids: [])
  end

end

app/controllers/parent_tasks_controller.rb
class ParentTasksController < ApplicationController
    before_action { :authenticate_user! || :authenticate_boss!}
    # before_action :authenticate_boss!, only: [:show, :index]

    def index
        # @parent_tasks = current_user.parent_tasks
        @parent_tasks = current_user.parent_tasks.order(parent_deadline: "ASC")
    end
    def show
        @parent_task = ParentTask.find(params[:id])
        @task_comments = @parent_task.task_comments
        @task_comment = TaskComment.new
    end
    def done
        @parent_task = ParentTask.find(params[:id])
        @parent_task.parent_done = 0
        @parent_task.save
        @child_tasks = ChildTask.where(parent_task_id: @parent_task.id)
        @child_tasks.each do |child_task|
            if child_task.done == nil

                child_task.done = 0
                child_task.finish_time = Time.now
                child_task.save
            end
        end
        redirect_to parent_tasks_path
    end
    def cansel
        @parent_task = ParentTask.find(params[:id])
        @parent_task.parent_done = nil
        @parent_task.save
        redirect_to parent_tasks_path
    end
    def new
        @parent_task = ParentTask.new
    end
    def create
        @parent_task = ParentTask.new(parent_task_params)
        @parent_task.user_id = current_user.id
        if @parent_task.save
            flash[:success] = 'タスクを作成しました'
            redirect_to parent_tasks_path
        end
    end
    def destroy
        @parent_task = ParentTask.find(params[:id])
        @parent_task.destroy
        redirect_to parent_tasks_path
    end

    private

    def parent_task_params
        params.require(:parent_task).permit(:title, :explanation, :parent_deadline, :self_evaluate)
    end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action { :authenticate_user! || :authenticate_boss!}

  # def index
  #   @teams = current_boss.teams
  # end

  def show
    # binding.pry
    @team=Team.find(params[:id])
    # binding.pry
  end

  # def new
  #   # @team = Team.where(team_params)
  #   @organization = Organization.new(team_params)
  # end

  # def create
  #   # binding.pry
  #   # @team = Team.new(team_params)
  #   @team = Team.where(team_params)
  # end

  # def destroy
  # end

  # private
  # def team_params
  #   # binding.pry
  #   params.permit(boss_ids:[])
  # end

end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action { :authenticate_user! || :authenticate_boss!}
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @parent_tasks=ParentTask.where(user_id: @user.id).order(parent_deadline: "ASC")
    # binding.pry
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bosses_helper.rb
module BossesHelper
end

app/helpers/child_tasks_helper.rb
module ChildTasksHelper
end

app/helpers/parent_tasks_helper.rb
module ParentTasksHelper
end

app/helpers/task_comment_helper.rb
module TaskCommentHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/parent_tasks/index.html.erb
<%= stylesheet_link_tag "common", :media => "all" %>
<% if user_signed_in? %>
    <h2><%= current_user.name%>のタスク一覧</h2>
<% elsif boss_signed_in? %>
    <h2><%= current_boss.name%>のタスク一覧表示</h2>
<% end %>
<button type="button" class="btn btn-primary parent-task-new " onclick="location.href='/parent_tasks/new'">タスク新規作成</button><br>

<% @parent_tasks.each do |parent_task| %>
  <div class="card border-secondary mb-5" style="width: 30rem;">
      <div class="card-header bg-light ">
      <div class="row">
        <div class="col-6">
          <div class="font-weight-bold">
              「<%= parent_task.title %>」
          </div>
          <%= link_to "タスク詳細", parent_task_path(parent_task), class: 'btn btn-link' %></br>
          <h5>サブタスク数： <%= parent_task.child_tasks.count %></h5>
        </div>
        <div class='col-5'>
         <% if parent_task.parent_done %>
                <%= button_to '完了済み', cansel_parent_task_path(id: parent_task.id), class: 'btn btn-success' %>
            <% else %>
                <%= button_to '完了にする', done_parent_task_path(id: parent_task.id), class: 'btn btn-primary' %>
            <% end %>
            <%= button_to 'Delete', parent_task_path(id: parent_task.id), method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %>
        </div>
        </div>
      </div>
      <div class="card-body">
          タスク概要：<%= parent_task.explanation %>
          <ul class="list-group list-group-flush">
              <li class="list-group-item">入力時刻:<%= parent_task.updated_at %></li>
              <li class="list-group-item">締め切り:<%= parent_task.parent_deadline %></li>
              <% if parent_task.self_evaluate == 0 %>
              <li class="list-group-item">自己評価:うまく切り分けられた</li>
              <% elsif parent_task.self_evaluate == 1 %>
              <li class="list-group-item">自己評価:普通</li>
              <% elsif parent_task.self_evaluate == 2 %>
              <li class="list-group-item">自己評価:上司助けて</li>
              <% else %>
              <li class="list-group-item">入力されていません</li>
              <% end %>
          </ul>
          <div class="card-footer">
          <% if user_signed_in? %>
            <%= link_to "サブタスク新規作成", new_parent_task_child_task_path(parent_task), class: "btn btn-secondary" %> /
          <% end %>
            <%= link_to "サブタスク一覧画面", parent_task_child_tasks_path(parent_task), class: "btn btn-secondary" %>
          </div>
      </div>
  </div>
<% end %>

app/views/parent_tasks/new.html.erb
<div class="container text-center">
<%= link_to "タスク一覧へ", parent_tasks_path(@parent_task) %>
<h3>タスク作成ページ</h3>
<%= form_with model: @parent_task do |f| %>
    <div class= 'form-group'>
        <%= f.label :title, 'タイトル', class: "col-2" %>
        <%= f.text_field :title, class: "col-4" %>
    </div>
    <div class= 'form-group'>
        <%= f.label :explanation, '概要', class: "col-2" %>
        <%= f.text_area :explanation, class: "col-4" %>
    </div>
    <div class= 'form-group'>
        <%= f.label :parent_deadline, '締め切り日時', class: "col-2" %>
        <%= f.datetime_field :parent_deadline, class: "col-4" %>
    </div>
    <div class= 'form-group'>
        <%= f.label :self_evaluate, '切り分け具合', class: "col-2" %>
        <%= f.select :self_evaluate, [["めちゃ上手くいったこれからできそう", "0"], ["普通", "1"], ["上司助けて", "2"]], class: "col-4" %>
    </div>
        <%= f.button 'タスク登録', class: "btn btn-primary" %>
<% end %>
</div>

app/views/parent_tasks/show.html.erb
<div class='container'>
<% if user_signed_in? %>
  <%= link_to "タスク一覧へ", parent_tasks_path(@parent_task), class: 'btn btn-light' %>
<%end%>
<div class="card text-center ">
  <h2 class="card-header">「<%= @parent_task.title %>」の詳細ページ</h2>
  <div class="card-body">
    <h4>タスク概要：<%= @parent_task.explanation%></h4>
    <p>締め切り:<%= @parent_task.parent_deadline %></p>
      <% if @parent_task.self_evaluate == 0 %>
        <p>切り分けの自己評価:うまく切り分けられた</p>
      <% elsif @parent_task.self_evaluate == 1 %>
        <p>切り分けの自己評価:普通</p>
      <% elsif @parent_task.self_evaluate == 2 %>
        <p>切り分けの自己評価:上司助けて</p>
      <% else %>
        <p>入力されていません</p>
      <% end %>
    <p>タスク更新時刻：<%= @parent_task.updated_at %></p>

    <%= form_with(model: [@parent_task, @task_comment]) do |f| %>
      <%= f.text_area :parent_comment %><br>
        <%= f.submit 'コメントする', class: 'btn btn-primary' %>
      <% end %>
  </div>

<div class="bg-light card-footer">
  <h5>〜コメント一覧〜</h5>
  <% @task_comments.each do |task_comment| %>
    <div class="border border-black">
    <% if task_comment.parent_task_id && task_comment.parent_comment %>
      <%= task_comment.parent_comment %>
      <%= button_to 'Delete', parent_task_task_comment_path(parent_task_id: @parent_task.id, id: task_comment.id), method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %> 
    <% end %>
    </div>
    </ul>
  <% end %>
</div>

 <ul class="list-group list-group-flush"><% @parent_task.child_tasks.each do |child_task| %>
        <% if child_task.done %>
          <li class="list-group-item">サブタスク:<%= child_task.title %>  <%= button_to '完了済み', show_canceled_parent_task_child_tasks_path(@parent_task, id: child_task.id) %> </li>
        <% else %>
          <li class="list-group-item">サブタスク:<%= child_task.title %>  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal<%= child_task.id %>">完了にする</button></li>
        <% end %>
       <!--modal-->
        <div class="modal fade" id="exampleModal<%= child_task.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">お疲れ様でした</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    あなたはタスクを完了しました</br>
                    その気持ちの入力をしてください
                    <%= form_with url: show_result_finish_parent_task_child_tasks_path(parent_task_id: @parent_task.id, id: child_task.id) do |f| %>
                    <%= f.label :result, '上手にできたかどうか'%>
                    <%= f.select :result, [['しっかりやり切れた', 0], ['まあまあやり切れた', 1], ['壁にぶつかった', 2]] , class: 'form-control'%>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <%= f.submit '保存', class: "btn btn-primary" %>
                    <% end %>
                </div>
                </div>
            </div>
        </div>
        <% end %>
    </ul>