config/routes.rb
Rails.application.routes.draw do
  root :to => 'toppages#index'
  # resources :teams, only: [:new, :create, :destroy]
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  get '/bosses/new_team', to: 'bosses#new_team'
  patch '/bosses/new_team', to: 'bosses#post_team'

  devise_for :bosses, controllers: {
    registrations: 'bosses/registrations',
    sessions: 'bosses/sessions'
  }

  resources :bosses, only:[:index, :show, :edit, :update]
  resources :users, only:[:index, :show]
  resources :teams, only:[:show] #ボスがチームメンバーの親タスクをまとめて見る用のroutes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # root to: 'tasks'
  resources :parent_tasks do
    member do
      post :done
      post :cansel
    end
    resources :task_comments, only: [:create, :destroy]
    resources :child_tasks do
      collection do
        post :finished
        post :index_canceled
        post :show_canceled
        post :index_result_finish
        post :show_result_finish
      end
    end
  end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/child_task.rb
class ChildTask < ApplicationRecord
  belongs_to :parent_task
  has_many :task_comments, dependent: :destroy
end

app/controllers/child_tasks_controller.rb
class ChildTasksController < ApplicationController
    before_action { :authenticate_user! || :authenticate_boss!}

    def index
       @child_tasks = ChildTask.where(parent_task_id: params[:parent_task_id]).order(child_deadline: "ASC")
       @parent_task = ParentTask.find_by(id: params[:parent_task_id])
       @task_comment = TaskComment.new
       @child_tasks.each do |child_task|
        if child_task.done == nil
            @parent_task.parent_done = nil
            @parent_task.save
        end
       end
    end

    def show
       @child_task = ChildTask.find(params[:id])
       @task_comments = @child_task.task_comments
       @task_comment = TaskComment.new
    end

    def new
        @parent_task = ParentTask.find(params[:parent_task_id])
        @child_task = ChildTask.new
    end
    def create
        @child_task = ChildTask.new(child_task_params)
        @child_task.parent_task_id = params[:parent_task_id].to_i
        if @child_task.save
            flash[:success] = 'タスクを作成しました'
            redirect_to parent_task_child_tasks_path
        end
    end
    def destroy
        @child_task = ChildTask.find(params[:id])
        @child_task.destroy
        redirect_to parent_task_child_tasks_path
    end
    def edit
    end
    def update
    end
    def index_result_finish
        resulted
        if @child_task.save
            finished
            redirect_to parent_task_child_tasks_path
        end
    end
    def show_result_finish
        resulted
        if @child_task.save
            finished
            redirect_to parent_task_path(id: @child_task.parent_task.id)
        end
    end
    def index_canceled
        canceled
        redirect_to parent_task_child_tasks_path
    end
    def show_canceled
        canceled
        redirect_to parent_task_path(id: @child_task.parent_task.id)
    end

    private
    def canceled
        @child_task = ChildTask.find_by(id: params[:id])
        @child_task.done = nil
        @child_task.finish_time = nil
        @child_task.save
    end
    def resulted
        @child_task = ChildTask.find_by(id: params[:id])
        parent_task = ParentTask.find(params[:parent_task_id])
        @child_task.result = params[:result].to_i
    end
    def finished
        time = Time.now
        @child_task = ChildTask.find_by(id: params[:id])
        @child_task.finish_time = time
        add_hour = 10800
        if @child_task.save
            if @child_task.finish_time < @child_task.child_deadline
                @child_task.done = 0
                @child_task.save
            elsif @child_task.child_deadline + add_hour > @child_task.finish_time && @child_task.finish_time >= @child_task.child_deadline
                @child_task.done = 1
                @child_task.save
            elsif @child_task.finish_time >= @child_task.child_deadline + add_hour
                @child_task.done = 2
                @child_task.save
            end
        end
    end
    def child_task_params
        params.require(:child_task).permit(:title, :explanation, :child_deadline, :possibility)
    end

end

app/helpers/child_tasks_helper.rb
module ChildTasksHelper
end

app/views/child_tasks/index.html.erb
<h2>サブタスク一覧</h2>
<%= link_to "タスク一覧画面へ", parent_tasks_path %>
<br>
<% if user_signed_in? %>
    <%= link_to "サブタスク新規作成", new_parent_task_child_task_path(@parent_task), class: "btn btn-secondary" %>
<% end %>
<br>
<% @child_tasks.each do |child_task| %>
 <% if params[:parent_task_id].to_i == child_task.parent_task_id %>
<br>
<div class="card border-secondary mb-5" style="width: 30rem;">
   
    <div class="card-header bg-light ">
    <div class="row">
        <div class="col-7">
            <div class="font-weight-bold">
                サブタスク名：「<%= child_task.title %>」
            </div>
            <%= link_to "サブタスク詳細画面", parent_task_child_task_path(parent_task_id: child_task.parent_task_id, id: child_task.id) %></br>
        </div>
        <div class="col-5">
            <% if child_task.done %>
                <% if user_signed_in?%>
                    <%= button_to '完了済み', index_canceled_parent_task_child_tasks_path(@parent_task, id: child_task.id), class: 'btn btn-success' %> 
                <% else %>
                    <p>完了済み</p>
                <% end%>
             <% else %>
                <% if user_signed_in?%>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal<%= child_task.id %>">完了にする</button>  
                <% else %>
                    <h3 style="color:red">未完了</h3>
                <% end %>
             <% end %>
             <%= button_to 'Delete', parent_task_child_task_path(id: child_task.id), method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %>
            <div class="modal fade" id="exampleModal<%= child_task.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">お疲れ様でした</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            あなたはタスクを完了しました。今の達成感は？？<br>
                            <%= form_with url: index_result_finish_parent_task_child_tasks_path(parent_task_id: @parent_task.id, id: child_task.id) do |f| %>
                            <%= f.label :result, '達成感'%>：
                            <%= f.select :result, [['しっかりやり切れた', 0], ['まあまあやり切れた', 1], ['壁にぶつかった', 2]] , class: 'form-control'%>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <%= f.submit '保存', class: "btn btn-primary" %>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    <div class="card-body">
        タスク概要：<%= child_task.explanation %>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">締め切り：<%= child_task.child_deadline %></li>
        <% if child_task.possibility %>
                <% if child_task.done == 0 %>
                    <li class="list-group-item">達成可能性：間に合いそう</li>
                <% elsif child_task.done == 1 %>
                    <li class="list-group-item">達成可能性：分からない</li>
                <% elsif child_task.done == 2 %>
                    <li class="list-group-item">達成可能性：厳しい</li>
                <% end %>
        <% end %>
        <li class="list-group-item">終了時刻：<%= child_task.finish_time %></li>
        <% if child_task.finish_time %>
                <% if child_task.done == 0 %>
                    <li class="list-group-item">タスク結果：間に合った</li>
                <% elsif child_task.done == 1 %>
                    <li class="list-group-item">タスク結果：〆切後3h以内で間に合った</li>
                <% elsif child_task.done == 2 %>
                    <li class="list-group-item">タスク結果：〆切に間に合わなかった</li>
                <% end %>
        <% end %>
    </ul>
        
    <div class="card-footer">
        <%= form_with url: parent_task_task_comments_path(parent_task_id: params[:parent_task_id], id: child_task.id), model: [ParentTask.new, @task_comment], method: :post do |f| %>
            <%= f.text_area :child_comment %>
            <br>
            <%= f.submit 'コメントする', class: 'btn btn-primary' %>
        <% end %>
        
        <% child_task.task_comments.each do |child_task_comment| %>
            <div class="border-black border row">
            <div class='col-6'>
            <% if child_task_comment.child_task_id && child_task_comment.child_comment %>
                <% if child_task_comment.boss_id %>
                    投稿者：<%= child_task_comment.boss.name %>
                <% elsif child_task_comment.user_id %>
                    投稿者：<%= child_task_comment.user.name %>
                <% end %>
                <%= simple_format(child_task_comment.child_comment) %>
            </div>
            <div class='col-5'>
                <% if current_user == child_task_comment.user || current_boss == child_task_comment.boss %>
                <%= button_to '削除する', parent_task_task_comment_path(parent_task_id: @parent_task.id, id: child_task_comment.id), method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %>
                <% end %>
            </div>
            <% end %>
            </div>
        <% end %>
    <% end %>
    </div>
    </div>
</div>

<% end %>

app/views/child_tasks/new.html.erb
<div class="container text-center">
<%= link_to "タスク一覧へ", parent_tasks_path(@parent_task) %>
<h3>サブタスク作成ページ</h3>
<%= form_with model: [@parent_task, @child_task] do |f| %>
    <div class= 'form-group'>
        <%= f.label :title, 'タイトル', class: "col-2" %>
        <%= f.text_field :title, class: "col-4" %>
    </div>
    <div class= 'form-group'>
        <%= f.label :explanation, '概要', class: "col-2" %>
        <%= f.text_area :explanation, class: "col-4" %>
    </div>
    <div class= 'form-group'>
        <%= f.label :child_deadline, '締め切り日時', class: "col-2" %>
        <%= f.datetime_field :child_deadline, class: "col-4" %>
    </div>
    <div class= 'form-group'>
        <%= f.label :possibility, '間に合うかどうか', class: "col-2" %>
        <%= f.select :possibility, [["自信がある", "0"], ["まあまあ", "1"], ["自信がないです助けて！", "2"]], class: "col-4" %>
    </div>
        <%= f.submit 'Save', :class => 'btn btn-primary'%>
<% end %>

</div>

app/views/child_tasks/show.html.erb
<div class="container">
    <%= link_to "子タスク一覧へ", parent_task_child_tasks_path(parent_task_id: @child_task.parent_task_id) %>  
<div class="card text-center">
    <h2 class="card-header">「<%= @child_task.title %>」の詳細ページ</h2>
    <div class="card-body">
        <h4>タスク概要：<%= @child_task.explanation %></h4>
        <p>締め切り:<%= @child_task.child_deadline %></p>
        <% if @child_task.possibility == 0 %>
            <p>達成可能性:自信がある</p>
        <% elsif @child_task.possibility == 1 %>
            <p>達成可能性:まあまあ</p>
        <% else %>
            <p>達成可能性:自信がないです助けて</p>
        <% end %>
    </div>
</div>
</div>