config/routes.rb
Rails.application.routes.draw do
  root :to => 'toppages#index'
  # resources :teams, only: [:new, :create, :destroy]
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  get '/bosses/new_team', to: 'bosses#new_team'
  patch '/bosses/new_team', to: 'bosses#post_team'

  devise_for :bosses, controllers: {
    registrations: 'bosses/registrations',
    sessions: 'bosses/sessions'
  }

  resources :bosses, only:[:index, :show, :edit, :update]
  resources :users, only:[:index, :show]
  resources :teams, only:[:show] #ボスがチームメンバーの親タスクをまとめて見る用のroutes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # root to: 'tasks'
  resources :parent_tasks do
    member do
      post :done
      post :cansel
    end
    resources :task_comments, only: [:create, :destroy]
    resources :child_tasks do
      collection do
        post :finished
        post :index_canceled
        post :show_canceled
        post :index_result_finish
        post :show_result_finish
      end
    end
  end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boss.rb
class Boss < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :organizations, dependent: :destroy
  has_many :teams, through: :organizations, dependent: :destroy
  has_many :task_comments, dependent: :destroy
  # boss.supervise_teamsでチーム引っ張れる
end

app/models/child_task.rb
class ChildTask < ApplicationRecord
  belongs_to :parent_task
  has_many :task_comments, dependent: :destroy
end

app/models/manager.rb
class Manager < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/organization.rb
class Organization < ApplicationRecord
    belongs_to :team
    belongs_to :boss
end

app/models/parent_task.rb
class ParentTask < ApplicationRecord
    belongs_to :user
    has_many :child_tasks, dependent: :destroy
    has_many :task_comments, dependent: :destroy
end

app/models/task_comment.rb
class TaskComment < ApplicationRecord
  validates :parent_comment, length: { maximum: 255 }
  validates :child_comment, length: { maximum: 255 }

  belongs_to :user, optional: true
  belongs_to :parent_task, optional: true
  belongs_to :child_task, optional: true
  belongs_to :boss, optional: true
end

app/models/team.rb
class Team < ApplicationRecord

    has_many :users, dependent: :destroy
    has_many :organizations, dependent: :destroy
    has_many :bosses, through: :organizations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 50 }

  belongs_to :team
  has_many :parent_tasks, dependent: :destroy
  has_many :task_comments, dependent: :destroy
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action { :authenticate_user! || :authenticate_boss!}

  # def index
  #   @teams = current_boss.teams
  # end

  def show
    # binding.pry
    @team=Team.find(params[:id])
    # binding.pry
  end

  # def new
  #   # @team = Team.where(team_params)
  #   @organization = Organization.new(team_params)
  # end

  # def create
  #   # binding.pry
  #   # @team = Team.new(team_params)
  #   @team = Team.where(team_params)
  # end

  # def destroy
  # end

  # private
  # def team_params
  #   # binding.pry
  #   params.permit(boss_ids:[])
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action { :authenticate_user! || :authenticate_boss!}
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @parent_tasks=ParentTask.where(user_id: @user.id).order(parent_deadline: "ASC")
    # binding.pry
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bosses_helper.rb
module BossesHelper
end

app/helpers/child_tasks_helper.rb
module ChildTasksHelper
end

app/helpers/parent_tasks_helper.rb
module ParentTasksHelper
end

app/helpers/task_comment_helper.rb
module TaskCommentHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_ParentTaskIndexPartial.html.erb
<%= stylesheet_link_tag "common", :media => "all" %>
<button type="button" class="btn btn-primary parent-task-new " onclick="location.href='/parent_tasks/new'">タスク新規作成</button><br>

<% @parent_tasks.each do |parent_task| %>
  <div class="card border-secondary mb-5" style="width: 30rem;">
      <div class="card-header bg-light ">
      <div class="row">
        <div class="col-6">
          <div class="form-check">
              <input class="form-check-input" type="checkbox" id="#" checked>
              <label class="form-check-label font-weight-bold" for="#">「<%= parent_task.title %>」</label>
          </div>
          <%= link_to "タスク詳細", parent_task_path(parent_task) %></br>
        </div>
        </div>
      </div>
      <div class="card-body">
          タスク概要：<%= parent_task.explanation %>
          <ul class="list-group list-group-flush">
              <li class="list-group-item">入力時刻:<%= parent_task.updated_at %></li>
              <li class="list-group-item">締め切り:<%= parent_task.parent_deadline %></li>
              <% if parent_task.self_evaluate == 0 %>
              <li class="list-group-item">自己評価:うまく切り分けられた</li>
              <% elsif parent_task.self_evaluate == 1 %>
              <li class="list-group-item">自己評価:普通</li>
              <% elsif parent_task.self_evaluate == 2 %>
              <li class="list-group-item">自己評価:上司助けて</li>
              <% else %>
              <li class="list-group-item">入力されていません</li>
              <% end %>
          </ul>
          <div class="card-footer">
          <% if user_signed_in? %>
            <%= link_to "サブタスク新規作成", new_parent_task_child_task_path(parent_task), class: "btn btn-secondary" %> /
          <% end %>
            <%= link_to "サブタスク一覧画面", parent_task_child_tasks_path(parent_task), class: "btn btn-secondary" %>
          </div>
      </div>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<%= stylesheet_link_tag "background-image", :media => "all" %>
<%= stylesheet_link_tag "common", :media => "all" %>

<% if user_signed_in? || boss_signed_in? %>
  <nav class="navbar navbar-expand-sm bg-dark fixed-top">
    <!--TOPに戻るボタン-->
    <a class="navbar-brand text-white" href = "/">FUN&FUN&FUN</a>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <% if user_signed_in? %>
            <h2 class="nav-link text-white"><%= current_user.team.name %></h2>
          <% elsif boss_signed_in?%>
            <% current_boss.teams.each do |team|%>
              <%= link_to team.name, team_path(id: team.id), class: "text-white" %>
            <% end%>
          <% end %>
        </li>
      </ul> 
      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <% if user_signed_in?%>
                  <h5 class="text-white"> <%= current_user.name %></h5>
                <% elsif boss_signed_in?%>
                  <h5 class="text-white"> <%= current_boss.name %></h5>
                <% else %>
                  <p class="text-white">Sign Up or Login</p>
                <% end %>
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <% if user_signed_in?%>
                  <div class="text-center">
                    <div class="border-bottom border-secondary">
                      <%= link_to "Users", "/users"%>
                      <br> 
                    </div>
                    <div class="border-bottom border-secondary">  
                      <%= link_to "Profile", current_user%>
                      <br>
                    </div>
                      <%= link_to "User logout", destroy_user_session_path, method: :delete %>
                  </div>
                <% elsif boss_signed_in?%>
                  <div class="text-center">
                    <div class="border-bottom border-secondary">
                      <%= link_to "Profile", current_boss%>
                      <br>
                    </div>
                    <div class="border-bottom border-secondary">
                      <%= link_to "Bosses", "/bosses"%>
                      <br>
                    </div>
                      <%= link_to "Boss logout", destroy_boss_session_path, method: :delete %>
                  </div>  
                <% else%>
                < i user_signed_in || 
                <% end %>
              </div>
            </li>
        </ul>
      </div>
  </nav>
<% else%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  
    
  </body>
</html>